import '../utilities/index.js';
import '../doubleclick/index.js';
import '../draggable/index.js';
import '../inlineedit/index.js';
import '../resizable/index.js';
import '../sortable/index.js';
import './dockbar.js';
import './window.scss';
import './window.js';